### ISSUE TITLE
Feedback is zero-ed when switching track

### ISSUE THREAD

**Issue by finfa** [helgoboss/realearn#249]
Affected versions: from 1.12-pre4 to 2.8.0-pre4
Reaper version: 6.15

Hi. Thank you for Realearn.

**Background**:  I have several tracks with 4 Realearn each in "selected track" mode. They all output the feedback to the same midi output but on different channels. Each channel is mapped to a controller (more or less).

**Problem**: When I change the selected track by moving from a track on the bottom to a track on the top, some controllers have all knobs to zero.

It's all good when I change the selected track by moving from a track on the top to a track on the bottom. The controller knobs will remap to correctly represent the state of the parameters.

**Additional info**

I analysed the midi feedback. I noticed that when switching track there are 2 series of midi cc for each channel. A first series has all the values to 0. The second one has all the values of the parameters.

When I change channel from bottom to top, the 0-series arrives _after_ the value-series.

P.S.: I de-activated the Reaper option "Send MIDI note-offs when un-record-arming a track". In fact on projects without Realearn, I get no feedback at all when switching tracks.

I am available to give further debug data.

**Comment by finfa** [comment]
Edit: Issue happens from 1.12-pre5 to 2.8.0-pre4.

It works correctly on 1.12-pre4. Although the feedback is slower, I can see that every knob flickers to 0 before being set to the correct value.

**Comment by helgoboss** [comment]
Hi, thanks for reporting. A simple test project would be great.

**Comment by finfa** [comment]
Edit: problem starts with 1.12-pre4.

**Comment by finfa** [comment]
I guess you have to setup the in/out of each Realearn to your midi i/o

[DebugProject.zip](https://github.com/helgoboss/realearn/files/6184215/DebugProject.zip)

**Comment by finfa** [comment]
Moving from track 1 to track 2:

![image](https://user-images.githubusercontent.com/4535128/112034330-a5c02b80-8b3e-11eb-9050-a1c7b919c620.png)

Moving from track 3 to track 2:

![image](https://user-images.githubusercontent.com/4535128/112034460-ca1c0800-8b3e-11eb-82eb-88aeedc1704f.png)

**Comment by helgoboss** [comment]
Great, I will look into it! Very good that you determined the version in which the behavior changes.

**Comment by helgoboss** [comment]
Ah, different instances which use the same control elements! Interesting. If this worked once then just by coincidence.

I reproduced it and I want to support it.

**Comment by helgoboss** [comment]
I think the reason why this worked before that ReaLearn was much more sloppy "cleaning up" (zeroing feedback). Now it really likes to clean up, maybe a bit too much.

**Comment by helgoboss** [comment]
This should work in upcoming 2.8.0-pre6. I implemented a kind of orchestration logic that gives other ReaLearn instances the chance to "take over" sources once they are released instead of blindly sending zero feedback and running into instance order issues. This also avoids the superfluous zero feedback. Zero feedback will only be sent if there's no other ReaLearn instance which takes over the source.

**Comment by finfa** [comment]
I confirm that it works for me on the test project. I still experience issues with my big template. I suspect it's because of backward compatibility issues upgrading from 1.11.

**Comment by finfa** [comment]
Took a while, but I managed to isolate it :)

How to reproduce (with the included project):

Setup:
- Set Realearn on Track 1 to output to Controller 2 (or FX output) - keep FX input
- Set Realearns on Tracks 2 and 3 to input/output with Controller 1

Problem 1:
Feedback is not sent when switching tracks.

I suspect it has to do with the CC/Chan being the same. In such case, would it be possible to discriminate also for the output device when resolving the take-over? That would be my holy grail :) (I can elaborate further on why, don't want to be too verbose now). But I hope there are benefits also for a more regular usage (thinking of many controllers being on chan 1 by default)

Problem 2:
If you change Track 1 CC to a different one (which should clear any conflict), then feedback is not sent switching from track 1 to track 2.

Problem 3:
When creating a new mapping, if "input FX" is selected, the value of the mapping is unstable. This happens to me also on a blank project, when for example I try to create a track like Track 1 of the attached project.
[DebugProject_fx_in.zip](https://github.com/helgoboss/realearn/files/6215622/DebugProject_fx_in.zip)

I hope it's not too much trouble. I looked at the merge and seems some significant change, and I am grateful. I wish I could help with the code but it's beyond my reach. Doing my best with debugs :)

**Comment by helgoboss** [comment]
@finfa Thanks for isolating, I will have another look.

**Comment by helgoboss** [comment]
> Took a while, but I managed to isolate it :)
> 
> How to reproduce (with the included project):
> 
> Setup:
> 
> * Set Realearn on Track 1 to output to Controller 2 (or FX output) - keep FX input

Just wanted to point out that "FX output" has drawbacks. It can't participate in ReaLearn's multi-instance feedback orchestration. So this is not supposed to work. I will add a hint in the user guide.

So I tested it with feedback output to controller 2 directly.

> * Set Realearns on Tracks 2 and 3 to input/output with Controller 1
> 
> Problem 1:
> Feedback is not sent when switching tracks.

Okay, I test feedback only, not control. Because I want to ensure that no control weirdness is influencing the results. So I only click around in REAPER, don't actually press the buttons.

I observed the following:

1. Feedback for track 2 and 3 is not sent reliably, yes. When switching between track 2 and 3 it works but when switching to it from no track or track 1, it doesn't work.
2. Track 1 feedback works for me. When looking at the mapping, I would not expect any feedback to change. There's no `<Selected>` or `Track must be selected` or similar. So I think we can take track 1 totally out of the equation. 

> I suspect it has to do with the CC/Chan being the same. In such case, would it be possible to discriminate also for the output device when resolving the take-over? That would be my holy grail :) (I can elaborate further on why, don't want to be too verbose now). But I hope there are benefits also for a more regular usage (thinking of many controllers being on chan 1 by default)

The feedback device is already used to discriminate, that was the whole point of this change. And it only comes into play if the source is exactly the same (e.g. CC/Chan same). So either it doesn't work correctly for this case or it must have other reasons, I will look into it.

> Problem 2:
> If you change Track 1 CC to a different one (which should clear any conflict), then feedback is not sent switching from track 1 to track 2.

As pointed out above, I think track 1 is not relevant. It doesn't work either way.

> Problem 3:
> When creating a new mapping, if "input FX" is selected, the value of the mapping is unstable. This happens to me also on a blank project, when for example I try to create a track like Track 1 of the attached project.

I'm afraid I don't understand this. You mean, `<FX input>`, right? I tried but couldn't observe anything weird. What exactly does "unstable" mean? And is it the feedback or the parameter value?

**Comment by helgoboss** [comment]
pre7 will have mentioned Problem 1 fixed. Feel free to further comment on Problem 3.

**Comment by finfa** [comment]
I confirm that the problem is solved on my setup as well.
